### PR TITLE
Server creation: Only get node_id from allocation if it is missing

### LINKED ISSUE #1592: Unable to create servers with no allocation
Trying to create a server without an allocation fails to create due to node_id being blank

Image

### PR DESCRIPTION
**Pull request by Boy132**
Closes #1592

### CODE REVIEW

File: app/Services/Servers/ServerCreationService.php [hunk 1]
```diff
@@ -87,7 +87,7 @@ public function handle(array $data, ?DeploymentObject $deployment = null): Serve
                 $data['node_id'] = $nodes->first();
             }
         } else {
-            $data['node_id'] = Allocation::find($data['allocation_id'])?->node_id;
+            $data['node_id'] = $data['node_id'] ?? Allocation::find($data['allocation_id'])?->node_id;
```
Comment (rmartinoscar) [inline app/Services/Servers/ServerCreationService.php]:
```suggestion
            $data['node_id'] ??= Allocation::find($data['allocation_id'])?->node_id;
```

**Review by lancepioch — APPROVED** [review]
