### PR TITLE
Chunk `Sushi` inserts based on rows count

### LINKED ISSUE #1254: 500 Server Error: SQLite too many SQL variables when accessing folder with many files
### Current Behavior

SQLSTATE[HY000]: General error: 1 too many SQL variables
...
insert into "files" (...) values (...), (...), ...

### Expected Behavior

I need the folder to load properly without issue. The issue with the folder having too many files inside it, is causing an error 500 for myself and others when trying to access this folder. I need the error resolved.

This used to work fine in a previous update, but seems to have stopped working in a recent update.

### Steps to Reproduce

Create a folder which then contains more than the SQLLite variables limit and try accessing the folder in the panel via the "Files" section of the individual server hosted.

### Panel Version

1.0.0-beta19

### Wings Version

v1.0.0-beta11

### Games and/or Eggs Affected

_No response_

### Docker Image

_No response_

### Error Logs

```bash
SQLSTATE[HY000]: General error: 1 too many SQL variables
...
insert into "files" (...) values (...), (...), ...
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by rmartinoscar**
Closes #1254
image

Tested using, you exceed memory limit going higher then this
```sh
for i in {1..36000}; do touch $EPOCHREALTIME; done
```

### CODE REVIEW

File: app/Models/File.php [hunk 1]
```diff
@@ -181,6 +183,10 @@ public function getRows(): array
                     'mime_type' => $file['mime'],
                 ];
             }, $contents);
+
+            $this->sushiInsertChunkSize = min((int) floor(999 / count($this->getSchema())), count($rows));
```
Comment (Boy132) [inline app/Models/File.php:187]: Is there a reason you do this crazy math instead of just setting the chunk size to a fixed value? Like 50 or something?

Comment (rmartinoscar) [reply app/Models/File.php:187]: The more you chunk it the lower the loading so i rather only lower it when needed

**Review by Boy132 — APPROVED** [review]
