### PR TITLE
Fix `TRUSTED_PROXIES` with `*`

### LINKED ISSUE #1268: Setting the proxy to * via /admin/setting will cause a server error on the setting page.
### Current Behavior

It saves, and after it saves, it always gets a 500 server error.

### Expected Behavior

Make “*” as the allowed proxy, or deny the operation.

### Steps to Reproduce

If the Trusted Proxies field is not set, enter * and press Save.

### Panel Version

v1.0.0-beta19

### Wings Version

v1.0.0-beta11

### Games and/or Eggs Affected

_No response_

### Docker Image

_No response_

### Error Logs

```bash
https://paste.pelistuff.com/haRN
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by Boy132**
Closes #1268

### CODE REVIEW

File: app/Filament/Admin/Pages/Settings.php [hunk 1]
```diff
@@ -212,7 +213,7 @@ private function generalSettings(): array
                 ->separator()
                 ->splitKeys(['Tab', ' '])
                 ->placeholder(trans('admin/setting.general.trusted_proxies_help'))
-                ->default(env('TRUSTED_PROXIES', implode(',', config('trustedproxy.proxies'))))
+                ->default(env('TRUSTED_PROXIES', implode(',', Arr::wrap(config('trustedproxy.proxies')))))
```
Comment (rmartinoscar) [inline app/Filament/Admin/Pages/Settings.php:216]: implode seems unnecessary, can't you set default state as an array ?

Comment (Boy132) [reply app/Filament/Admin/Pages/Settings.php:216]: You're the one who added the implode :D
So I guess it's necessary

Comment (rmartinoscar) [reply app/Filament/Admin/Pages/Settings.php:216]: Nvm yes its needed cause even if the field isn't set its written in .env but no value is assigned

**Review by rmartinoscar — APPROVED** [review]
