### PR TITLE
fix: Enhance feedback notifications for egg actions

### LINKED ISSUE #1962: Improve error message when deleting eggs with dependencies
## Description

  When trying to delete an egg that has dependencies (servers using it, egg variables, etc.), the
  error message displayed is not helpful:

  > "Failed to delete 1 could not be deleted"

  This message doesn't explain **why** the deletion failed.

  ## Steps to Reproduce

  1. Create an egg
  2. Create a server using this egg
  3. Try to delete the egg via Admin > Eggs > Select egg > Bulk Actions > Delete Selected
  4. Confirm deletion
  5. See unhelpful error message

  ## Expected Behavior

  The error message should be more descriptive, for example:
  - "Cannot delete egg: 1 server(s) are currently using this egg"
  - "Cannot delete egg 'Mohist': Please delete or reassign the following servers first: [Server1,
  Server2]"

  ## Current Behavior

  Generic message "Failed to delete 1 could not be deleted" with no indication of the actual
  cause.

  ## Environment

  - Pelican Panel: latest (Docker image `ghcr.io/pelican-dev/panel:latest`)
  - Browser: Chrome/Firefox

  ## Additional Context

  This would greatly improve the admin UX by helping administrators understand what action they
  need to take before deleting an egg.

### PR DESCRIPTION
**Pull request by PalmarHealer**
Closes #1962

(I renamed the branch and it closed the PR. I was unable to re-open it)

### CODE REVIEW

File: app/Filament/Components/Actions/UpdateEggAction.php [hunk 1]
```diff
@@ -41,14 +41,16 @@ protected function setUp(): void
         $this->modalSubmitAction(fn (Action $action) => $action->color('danger'));
 
         $this->action(function (Egg $egg, EggImporterService $eggImporterService) {
+            $eggName = $egg->name;
+
```
Comment (lancepioch) [inline app/Filament/Components/Actions/UpdateEggAction.php]: Don't think we need the variable!

File: app/Filament/Admin/Resources/Eggs/Pages/ListEggs.php [hunk 2]
```diff
@@ -88,15 +90,47 @@ public function table(Table $table): Table
...
-                    ->before(fn (&$records) => $records = $records->filter(function ($egg) {
-                        /** @var Egg $egg */
-                        return $egg->servers_count <= 0;
-                    })),
+                    ->before(function (Collection &$records) {
+                        $eggsWithServers = $records->filter(fn (Egg $egg) => $egg->servers_count > 0);
+
+                        if ($eggsWithServers->isNotEmpty()) {
+                            $eggNames = $eggsWithServers->map(function (Egg $egg) {
+                                return sprintf('%s (%d server%s)', $egg->name, $egg->servers_count, $egg->servers_count > 1 ? 's' : '');
```
Comment (lancepioch) [inline app/Filament/Admin/Resources/Eggs/Pages/ListEggs.php]: Can be short fn instead
