### PR TITLE
Scope power buttons to current server

### LINKED ISSUE #831: Start & stop button starts & stops multiple servers
### Current Behavior

In the new client area if you have 2 servers that are both offline, and you press start on one of them, both will start.

Note: This does not happen in the old client side

https://github.com/user-attachments/assets/7cd951a1-beb6-44e4-9dbe-192bcb0ce756

### Expected Behavior

If you hit start only that server should start.

### Steps to Reproduce

1. Make 2 servers, I have 2 mumble servers (but was tested with BungeeCord)
2. check if both servers are offline (auto start maybe on)
afbeelding
3. Press start on one of them
afbeelding
4. See that they both start
5. Press stop on the container that started them both and see that both containers will go offline

Note it may only happen if you start and then stop a server and then try to start it again (so not the first time)

### Panel Version

main and v1.0.0-beta16

### Wings Version

master

### Games and/or Eggs Affected

All

### Docker Image

All

### Error Logs

```bash
Wings: https://paste.pelistuff.com/TYCW
Panel: https://paste.pelistuff.com/a2ER
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by lancepioch**
Fixes #831

### CODE REVIEW

**Review by RMartinOscar — APPROVED** [review]

File: app/Exceptions/Http/Server/ServerStateConflictException.php [hunk 1]
```diff
@@ -14,18 +14,15 @@ class ServerStateConflictException extends ConflictHttpException
...
-        } elseif ($server->status === ServerState::RestoringBackup) {
-            $message = 'This server is currently restoring from a backup, please try again later.';
-        } elseif (!is_null($server->transfer)) {
-            $message = 'This server is currently being transferred to a new machine, please try again later.';
-        }
+        $message = match (true) {
+            $server->transfer !== null => 'This server is currently being transferred to a new machine, please try again later.',
+            $server->isSuspended() => 'This server is currently suspended and the functionality requested is unavailable.',
+            $server->node->isUnderMaintenance() => 'The node of this server is currently under maintenance and the functionality requested is unavailable.',
+            $server->status === ServerState::InstallFailed => 'The server installation has failed.',
```
Comment (Boy132) [inline app/Exceptions/Http/Server/ServerStateConflictException.php:21]: A failed install is not a "conflict state".
