### PR TITLE
Fix 500 when viewing node

### LINKED ISSUE #1143: Undefined array key "disk_total"
### Current Behavior

There is a 500 error when adding a new node.

### Expected Behavior

No error.

### Steps to Reproduce

Add a new Error

### Panel Version

canary (82b0aff)

### Wings Version

does not apply

### Games and/or Eggs Affected

_No response_

### Docker Image

_No response_

### Error Logs

```bash
Undefined array key "disk_total" (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php) (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php) (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php) (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php) (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php) (View: /var/www/pelican/resources/views/filament/components/node-storage-chart.blade.php)
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

### PR DESCRIPTION
**Pull request by notAreYouScared**
Catches 500 when connecting to a node, that's already a wings server? Not sure how to explain it.

#1075 Should've fixed it, but it still exists.

Closes #1143

### CODE REVIEW

File: app/Models/Node.php [hunk 1]
```diff
@@ -367,11 +367,17 @@ public function statistics(): array
         try {
             $this->systemInformation();
```
Comment (rmartinoscar) [inline app/Models/Node.php:368]:
```suggestion
```
This is useless then

File: app/Models/Node.php [hunk 2]
```diff
@@ -367,11 +367,17 @@ public function statistics(): array
...
+                ->json();
+
+            if ($data['memory_total']) {
+                return $data;
+            } else {
+                return $default;
+            }
         } catch (Exception) {
             return $default;
         }
```
Comment (rmartinoscar) [inline app/Models/Node.php:383]:
```suggestion
            if ($data['memory_total']) {
                return $data;
        } catch (Exception) {
        }
        return $default;
```

Comment (notAreYouScared) [reply app/Models/Node.php:383]: If theres no exception... what are we returning? Nothing? We'd be right back to square on where somthing responds.... and its in json...

Comment (rmartinoscar) [reply app/Models/Node.php:383]: > If theres no exception... what are we returning? Nothing? We'd be right back to square on where somthing responds.... and its in json...
That's why i moved the `return $default` out of the catch

Comment (notAreYouScared) [reply app/Models/Node.php:383]: Missed that, my bad

**Review by lancepioch — APPROVED** [review]
