### PR TITLE
Fix/suspend server offline node

### LINKED ISSUE #867: Can't suspend server if node is Offline

### PR DESCRIPTION
**Pull request by RMartinOscar**
Closes #867
image
image

### CODE REVIEW

File: app/Http/Controllers/Api/Application/Servers/ServerManagementController.php [hunk 1]
```diff
@@ -32,7 +32,7 @@ public function __construct(
      */
     public function suspend(ServerWriteRequest $request, Server $server): Response
     {
-        $this->suspensionService->toggle($server);
+        $this->suspensionService->handle($server);
```
Comment (lancepioch) [inline app/Http/Controllers/Api/Application/Servers/ServerManagementController.php:35]: Let's be explicit:

```suggestion
        $this->suspensionService->handle($server, SuspensionService::ACTION_SUSPEND);
```

File: app/Services/Servers/SuspensionService.php [hunk 2]
```diff
@@ -27,7 +28,7 @@ public function __construct(
      *
      * @throws \Throwable
      */
-    public function toggle(Server $server, string $action = self::ACTION_SUSPEND): void
+    public function handle(Server $server, string $action = self::ACTION_SUSPEND): void
```
Comment (lancepioch) [inline app/Services/Servers/SuspensionService.php:31]: I'd like to remove the default action, while we're in here. Also let's switch it from a string to an enum!

```suggestion
    public function handle(Server $server, SuspendAction $action): void
```

File: app/Services/Servers/SuspensionService.php [hunk 3]
```diff
@@ -55,11 +56,7 @@ public function toggle(Server $server, string $action = self::ACTION_SUSPEND): v
         try {
             // Tell daemon to re-sync the server state.
             $this->daemonServerRepository->setServer($server)->sync();
-        } catch (\Exception $exception) {
-            // Rollback the server's suspension status if daemon fails to sync the server.
-            $server->update([
-                'status' => $isSuspending ? null : ServerState::Suspended,
-            ]);
+        } catch (ConnectionException $exception) {
```
Comment (lancepioch) [inline app/Services/Servers/SuspensionService.php:59]: I agree with this change. Yes, wings does need to know that the server is suspended, but if it's currently not connected, it will simply sync that correctly when it reconnects!

**Review by lancepioch — CHANGES_REQUESTED** [review]

**Review by lancepioch — APPROVED** [review]
