### PR TITLE
Fix deleted users being shown as "System" in activity log

### LINKED ISSUE #569: Deleted users show as `System` in activity logs
### Discussed in https://github.com/pelican-dev/panel/discussions/567

<div type='discussions-op-text'>

<sup>Originally posted by **JoanFont1212** August 30, 2024</sup>
Someone told me to open here a bug and i didn't see where to click, so i'm using this, i'm sorry.
When a user does something in activity, delete files, etc... And you delete the user, shows the activity as the system's one with the user IP, it's a little bit confusing.
Here is some proof.
image
</div>

### PR DESCRIPTION
**Pull request by GaviDroselj**
Shows deleted users as "Deleted user" and changes their icon to "user-off"

image

Closes #569

### CODE REVIEW

File: app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php [hunk 1]
```diff
@@ -42,7 +42,11 @@ public function table(Table $table): Table
                 TextColumn::make('user')
                     ->state(function (ActivityLog $activityLog) use ($server) {
                         if (!$activityLog->actor instanceof User) {
-                            return 'System';
+                            if ($activityLog->actor_id == null) {
+                                return 'System';
+                            } else {
+                                return 'Deleted user';
+                            }
```
Comment (Boy132) [inline app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php:49]:
```suggestion
                            return $activityLog->actor_id === null ? 'System' : 'Deleted user';
```

File: app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php [hunk 2]
```diff
@@ -72,7 +76,11 @@ public function table(Table $table): Table
                         TextInput::make('user')
                             ->formatStateUsing(function (ActivityLog $activityLog) use ($server) {
                                 if (!$activityLog->actor instanceof User) {
-                                    return 'System';
+                                    if ($activityLog->actor_id == null) {
+                                        return 'System';
+                                    } else {
+                                        return 'Deleted user';
+                                    }
```
Comment (Boy132) [inline app/Filament/Server/Resources/ActivityResource/Pages/ListActivities.php:83]:
```suggestion
                                    return $activityLog->actor_id === null ? 'System' : 'Deleted user';
```

**Review by Boy132 — CHANGES_REQUESTED** [review]
Looks good, just some small styling changes.

**Review by Boy132 — APPROVED** [review]
LGTM, thank you for your contribution!

File: app/Models/ActivityLog.php [hunk 3]
```diff
@@ -153,7 +153,11 @@ public function getIcon(): string
             return 'tabler-api';
         }
 
-        return $this->actor instanceof User ? 'tabler-user' : 'tabler-device-desktop';
+        if ($this->actor instanceof User) {
+            return 'tabler-user';
+        }
+
+        return $this->actor_id !== null ? 'tabler-user-off' : 'tabler-device-desktop';
```
Comment (RMartinOscar) [inline app/Models/ActivityLog.php:160]:
```suggestion
        return $this->actor_id === null ? 'tabler-device-desktop' : 'tabler-user-off';
```

**Review by RMartinOscar — CHANGES_REQUESTED** [review]

**Review by rmartinoscar — APPROVED** [review]
